/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AsanaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/api.ts
var BASE = "https://app.asana.com/api/1.0";
var TASK_FIELDS = "gid,name,notes,completed,due_on,assignee.name,assignee.gid,projects.gid,projects.name,tags.gid,tags.name,permalink_url,created_at,modified_at,custom_fields.gid,custom_fields.name,custom_fields.display_value";
var AsanaAPI = class {
  constructor(pat) {
    this.pat = pat;
  }
  async request(path, options = {}) {
    var _a;
    const res = await fetch(`${BASE}${path}`, {
      ...options,
      headers: {
        Authorization: `Bearer ${this.pat}`,
        "Content-Type": "application/json",
        ...(_a = options.headers) != null ? _a : {}
      }
    });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(`Asana API error ${res.status}: ${body}`);
    }
    const json = await res.json();
    return json.data;
  }
  async getMe() {
    return this.request(
      "/users/me?opt_fields=gid,name,email,workspaces.gid,workspaces.name"
    );
  }
  async getTask(gid) {
    return this.request(`/tasks/${gid}?opt_fields=${TASK_FIELDS}`);
  }
  async getMyTasks(workspaceGid) {
    await this.getMe();
    return this.request(
      `/tasks?assignee=me&workspace=${workspaceGid}&completed_since=now&opt_fields=${TASK_FIELDS}&limit=100`
    );
  }
  async getProjectTasks(projectGid) {
    return this.request(
      `/projects/${projectGid}/tasks?opt_fields=${TASK_FIELDS}&limit=100`
    );
  }
  async searchTasks(workspaceGid, query) {
    const params = new URLSearchParams({
      text: query,
      opt_fields: TASK_FIELDS,
      limit: "20"
    });
    return this.request(`/workspaces/${workspaceGid}/tasks/search?${params}`);
  }
  async getProjects(workspaceGid) {
    return this.request(
      `/projects?workspace=${workspaceGid}&opt_fields=gid,name,color,permalink_url&limit=100`
    );
  }
  async getWorkspaces() {
    const me = await this.getMe();
    return me.workspaces;
  }
  async createTask(params) {
    return this.request(`/tasks?opt_fields=${TASK_FIELDS}`, {
      method: "POST",
      body: JSON.stringify({ data: params })
    });
  }
  async completeTask(gid) {
    return this.request(`/tasks/${gid}?opt_fields=${TASK_FIELDS}`, {
      method: "PUT",
      body: JSON.stringify({ data: { completed: true } })
    });
  }
  async uncompleteTask(gid) {
    return this.request(`/tasks/${gid}?opt_fields=${TASK_FIELDS}`, {
      method: "PUT",
      body: JSON.stringify({ data: { completed: false } })
    });
  }
  async updateTask(gid, fields) {
    return this.request(`/tasks/${gid}?opt_fields=${TASK_FIELDS}`, {
      method: "PUT",
      body: JSON.stringify({ data: fields })
    });
  }
  extractGidFromUrl(url) {
    const match = url.match(/\/(\d+)\/?(?:\?|$)/);
    return match ? match[1] : null;
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");
var AsanaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Asana Plugin Settings" });
    new import_obsidian.Setting(containerEl).setName("Personal Access Token").setDesc("Create one at Account Settings \u2192 Apps \u2192 Personal Access Tokens in Asana.").addText(
      (text) => text.setPlaceholder("0/xxxxxxxxxxxxxxxxxxxxxxxxxxxx").setValue(this.plugin.settings.pat).onChange(async (value) => {
        this.plugin.settings.pat = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Verify connection").setDesc("Test your PAT and load available workspaces.").addButton(
      (btn) => btn.setButtonText("Connect").setCta().onClick(async () => {
        var _a, _b;
        btn.setButtonText("Connecting\u2026").setDisabled(true);
        try {
          const api = new AsanaAPI(this.plugin.settings.pat);
          const me = await api.getMe();
          new import_obsidian.Notice(`Connected as ${me.name}`);
          this.plugin.settings.defaultWorkspaceGid = this.plugin.settings.defaultWorkspaceGid || ((_a = me.workspaces[0]) == null ? void 0 : _a.gid) || "";
          this.plugin.settings.defaultWorkspaceName = this.plugin.settings.defaultWorkspaceName || ((_b = me.workspaces[0]) == null ? void 0 : _b.name) || "";
          await this.plugin.saveSettings();
          this.display();
        } catch (e) {
          new import_obsidian.Notice(`Connection failed: ${e.message}`);
        } finally {
          btn.setButtonText("Connect").setDisabled(false);
        }
      })
    );
    containerEl.createEl("h3", { text: "Defaults" });
    new import_obsidian.Setting(containerEl).setName("Default workspace GID").setDesc("Workspace GID to use when none is specified in a code block. Find it in your Asana URL.").addText(
      (text) => text.setPlaceholder("123456789").setValue(this.plugin.settings.defaultWorkspaceGid).onChange(async (value) => {
        this.plugin.settings.defaultWorkspaceGid = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default workspace name").setDesc("Display name for the default workspace.").addText(
      (text) => text.setPlaceholder("My Organisation").setValue(this.plugin.settings.defaultWorkspaceName).onChange(async (value) => {
        this.plugin.settings.defaultWorkspaceName = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default project GID").setDesc("Pre-selected project GID when creating tasks. Leave blank for workspace-level tasks.").addText(
      (text) => text.setPlaceholder("987654321").setValue(this.plugin.settings.defaultProjectGid).onChange(async (value) => {
        this.plugin.settings.defaultProjectGid = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default assignee").setDesc('Use "me" to assign to yourself, or paste a user GID.').addText(
      (text) => text.setPlaceholder("me").setValue(this.plugin.settings.defaultAssignee).onChange(async (value) => {
        this.plugin.settings.defaultAssignee = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Display" });
    new import_obsidian.Setting(containerEl).setName("Show completed tasks in lists").setDesc("When enabled, task list views will include completed tasks.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCompletedTasks).onChange(async (value) => {
        this.plugin.settings.showCompletedTasks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Task list refresh interval (seconds)").setDesc("How often the task list sidebar auto-refreshes. Set to 0 to disable.").addText(
      (text) => text.setPlaceholder("300").setValue(String(this.plugin.settings.taskListRefreshInterval)).onChange(async (value) => {
        const n = parseInt(value);
        if (!isNaN(n)) {
          this.plugin.settings.taskListRefreshInterval = n;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  pat: "",
  defaultWorkspaceGid: "",
  defaultWorkspaceName: "",
  defaultProjectGid: "",
  defaultProjectName: "",
  defaultAssignee: "me",
  showCompletedTasks: false,
  taskListRefreshInterval: 300
};

// src/renderers/TaskEmbedRenderer.ts
var import_obsidian2 = require("obsidian");
var TaskEmbedRenderer = class extends import_obsidian2.MarkdownRenderChild {
  constructor(containerEl, source, settings) {
    super(containerEl);
    this.source = source;
    this.settings = settings;
  }
  async onload() {
    await this.render();
  }
  async render() {
    this.containerEl.empty();
    const loading = this.containerEl.createDiv({ cls: "asana-loading" });
    loading.setText("Loading Asana task\u2026");
    try {
      const gid = this.resolveGid(this.source.trim());
      if (!gid) {
        this.renderError("Could not parse task ID from: " + this.source.trim());
        return;
      }
      const api = new AsanaAPI(this.settings.pat);
      const task = await api.getTask(gid);
      this.containerEl.empty();
      this.renderTask(task);
    } catch (e) {
      this.renderError(e.message);
    }
  }
  resolveGid(raw) {
    if (/^\d+$/.test(raw))
      return raw;
    const match = raw.match(/\/(\d+)\/?(?:\?|$|\/f)/);
    return match ? match[1] : null;
  }
  renderTask(task) {
    const wrap = this.containerEl.createDiv({ cls: "asana-task-embed" });
    const header = wrap.createDiv({ cls: "asana-task-header" });
    const checkbox = header.createEl("input", {
      type: "checkbox",
      cls: "asana-task-checkbox"
    });
    checkbox.checked = task.completed;
    checkbox.addEventListener("change", async () => {
      try {
        const api = new AsanaAPI(this.settings.pat);
        if (checkbox.checked) {
          await api.completeTask(task.gid);
        } else {
          await api.uncompleteTask(task.gid);
        }
        titleEl.toggleClass("asana-completed", checkbox.checked);
      } catch (e) {
        checkbox.checked = !checkbox.checked;
      }
    });
    const titleEl = header.createEl("a", {
      text: task.name,
      href: task.permalink_url,
      cls: "asana-task-title"
    });
    if (task.completed)
      titleEl.addClass("asana-completed");
    const meta = wrap.createDiv({ cls: "asana-task-meta" });
    if (task.assignee) {
      meta.createSpan({
        cls: "asana-meta-chip asana-assignee",
        text: `\u{1F464} ${task.assignee.name}`
      });
    }
    if (task.due_on) {
      const due = new Date(task.due_on);
      const overdue = !task.completed && due < /* @__PURE__ */ new Date();
      meta.createSpan({
        cls: "asana-meta-chip asana-due" + (overdue ? " asana-overdue" : ""),
        text: `\u{1F4C5} ${task.due_on}`
      });
    }
    if (task.projects.length > 0) {
      const proj = meta.createSpan({ cls: "asana-meta-chip asana-project" });
      proj.setText("\u{1F4C1} " + task.projects.map((p) => p.name).join(", "));
    }
    if (task.notes) {
      const notes = wrap.createDiv({ cls: "asana-task-notes" });
      notes.setText(task.notes.length > 300 ? task.notes.slice(0, 300) + "\u2026" : task.notes);
    }
    if (task.custom_fields && task.custom_fields.length > 0) {
      const fields = wrap.createDiv({ cls: "asana-custom-fields" });
      for (const cf of task.custom_fields) {
        if (!cf.display_value)
          continue;
        const row = fields.createDiv({ cls: "asana-cf-row" });
        row.createSpan({ cls: "asana-cf-name", text: cf.name + ":" });
        row.createSpan({ cls: "asana-cf-value", text: cf.display_value });
      }
    }
  }
  renderError(msg) {
    this.containerEl.empty();
    const err = this.containerEl.createDiv({ cls: "asana-error" });
    err.setText("Asana: " + msg);
  }
};

// src/renderers/TaskListRenderer.ts
var import_obsidian3 = require("obsidian");
var TaskListRenderer = class extends import_obsidian3.MarkdownRenderChild {
  constructor(containerEl, source, settings) {
    super(containerEl);
    this.source = source;
    this.settings = settings;
    this.options = this.parseOptions(source);
  }
  async onload() {
    await this.render();
  }
  parseOptions(source) {
    const opts = {
      mode: "my-tasks",
      workspaceGid: this.settings.defaultWorkspaceGid
    };
    for (const line of source.split("\n")) {
      const [key, ...rest] = line.split(":").map((s) => s.trim());
      const value = rest.join(":").trim();
      if (!value)
        continue;
      switch (key) {
        case "mode":
          opts.mode = value;
          break;
        case "project":
          opts.projectGid = value;
          break;
        case "workspace":
          opts.workspaceGid = value;
          break;
        case "limit":
          opts.limit = parseInt(value) || 20;
          break;
        case "show-completed":
          opts.showCompleted = value === "true";
          break;
        case "title":
          opts.title = value.replace(/^["']|["']$/g, "");
          break;
      }
    }
    return opts;
  }
  async render() {
    var _a;
    this.containerEl.empty();
    const loading = this.containerEl.createDiv({ cls: "asana-loading" });
    loading.setText("Loading tasks\u2026");
    try {
      const api = new AsanaAPI(this.settings.pat);
      let tasks = [];
      if (this.options.mode === "project" && this.options.projectGid) {
        tasks = await api.getProjectTasks(this.options.projectGid);
      } else if (this.options.workspaceGid) {
        tasks = await api.getMyTasks(this.options.workspaceGid);
      } else {
        throw new Error(
          'No workspace GID set. Add "workspace: <gid>" to the block or configure a default in settings.'
        );
      }
      const showCompleted = (_a = this.options.showCompleted) != null ? _a : this.settings.showCompletedTasks;
      if (!showCompleted) {
        tasks = tasks.filter((t) => !t.completed);
      }
      if (this.options.limit) {
        tasks = tasks.slice(0, this.options.limit);
      }
      this.containerEl.empty();
      this.renderList(tasks, api);
    } catch (e) {
      this.containerEl.empty();
      const err = this.containerEl.createDiv({ cls: "asana-error" });
      err.setText("Asana: " + e.message);
    }
  }
  renderList(tasks, api) {
    const wrap = this.containerEl.createDiv({ cls: "asana-task-list" });
    const titleText = this.options.title || (this.options.mode === "project" ? "Project Tasks" : "My Tasks");
    const titleRow = wrap.createDiv({ cls: "asana-list-header" });
    titleRow.createEl("h4", { text: titleText, cls: "asana-list-title" });
    const refreshBtn = titleRow.createEl("button", {
      cls: "asana-refresh-btn",
      text: "\u27F3",
      title: "Refresh"
    });
    refreshBtn.addEventListener("click", () => this.render());
    if (tasks.length === 0) {
      wrap.createDiv({ cls: "asana-empty", text: "No tasks found." });
      return;
    }
    const list = wrap.createEl("ul", { cls: "asana-task-list-items" });
    for (const task of tasks) {
      const li = list.createEl("li", { cls: "asana-task-list-item" });
      const checkbox = li.createEl("input", {
        type: "checkbox",
        cls: "asana-task-checkbox"
      });
      checkbox.checked = task.completed;
      const info = li.createDiv({ cls: "asana-task-list-info" });
      const link = info.createEl("a", {
        text: task.name,
        href: task.permalink_url,
        cls: "asana-task-list-name"
      });
      if (task.completed)
        link.addClass("asana-completed");
      const sub = info.createDiv({ cls: "asana-task-list-sub" });
      if (task.due_on) {
        const overdue = !task.completed && new Date(task.due_on) < /* @__PURE__ */ new Date();
        sub.createSpan({
          cls: "asana-meta-chip asana-due" + (overdue ? " asana-overdue" : ""),
          text: task.due_on
        });
      }
      if (task.assignee) {
        sub.createSpan({ cls: "asana-meta-chip", text: task.assignee.name });
      }
      checkbox.addEventListener("change", async () => {
        try {
          if (checkbox.checked) {
            await api.completeTask(task.gid);
          } else {
            await api.uncompleteTask(task.gid);
          }
          link.toggleClass("asana-completed", checkbox.checked);
        } catch (e) {
          checkbox.checked = !checkbox.checked;
          new import_obsidian3.Notice("Failed to update task: " + e.message);
        }
      });
    }
  }
};

// src/modals/CreateTaskModal.ts
var import_obsidian4 = require("obsidian");
var CreateTaskModal = class extends import_obsidian4.Modal {
  constructor(app, settings, onCreated) {
    super(app);
    this.settings = settings;
    this.onCreated = onCreated;
    this.name = "";
    this.notes = "";
    this.dueOn = "";
    this.projectGid = "";
    this.workspaceGid = "";
    this.assignee = "";
    this.workspaces = [];
    this.workspaceGid = settings.defaultWorkspaceGid;
    this.projectGid = settings.defaultProjectGid;
    this.assignee = settings.defaultAssignee;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Create Asana Task" });
    this.loadWorkspacesAndProjects();
    new import_obsidian4.Setting(contentEl).setName("Task name").setClass("asana-modal-required").addText((text) => text.setPlaceholder("Task name").setValue(this.name).onChange((v) => this.name = v));
    new import_obsidian4.Setting(contentEl).setName("Description").addTextArea(
      (ta) => ta.setPlaceholder("Optional description\u2026").setValue(this.notes).onChange((v) => this.notes = v)
    );
    new import_obsidian4.Setting(contentEl).setName("Due date").addText(
      (text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.dueOn).onChange((v) => this.dueOn = v)
    );
    new import_obsidian4.Setting(contentEl).setName("Assignee").setDesc('Use "me" for yourself, or paste a user GID.').addText(
      (text) => text.setPlaceholder("me").setValue(this.assignee).onChange((v) => this.assignee = v)
    );
    new import_obsidian4.Setting(contentEl).setName("Workspace GID").setDesc("Leave blank to use the default workspace.").addText(
      (text) => text.setPlaceholder(this.settings.defaultWorkspaceGid).setValue(this.workspaceGid).onChange((v) => {
        this.workspaceGid = v;
      })
    );
    new import_obsidian4.Setting(contentEl).setName("Project GID").setDesc("Optional. Leave blank for a workspace-level task.").addText(
      (text) => text.setPlaceholder(this.settings.defaultProjectGid).setValue(this.projectGid).onChange((v) => this.projectGid = v)
    );
    new import_obsidian4.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create Task").setCta().onClick(async () => {
        if (!this.name.trim()) {
          new import_obsidian4.Notice("Task name is required.");
          return;
        }
        btn.setButtonText("Creating\u2026").setDisabled(true);
        try {
          const api = new AsanaAPI(this.settings.pat);
          const wsGid = this.workspaceGid || this.settings.defaultWorkspaceGid;
          const projGid = this.projectGid || this.settings.defaultProjectGid;
          const task = await api.createTask({
            name: this.name.trim(),
            notes: this.notes.trim() || void 0,
            due_on: this.dueOn.trim() || void 0,
            workspace: wsGid || void 0,
            projects: projGid ? [projGid] : void 0,
            assignee: this.assignee.trim() || "me"
          });
          new import_obsidian4.Notice(`Created: ${task.name}`);
          if (this.onCreated) {
            this.onCreated(task.permalink_url, task.name);
          }
          this.close();
        } catch (e) {
          new import_obsidian4.Notice("Failed to create task: " + e.message);
          btn.setButtonText("Create Task").setDisabled(false);
        }
      })
    );
  }
  async loadWorkspacesAndProjects() {
    try {
      const api = new AsanaAPI(this.settings.pat);
      this.workspaces = await api.getWorkspaces();
    } catch (e) {
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/TaskSearchModal.ts
var import_obsidian5 = require("obsidian");
var TaskSearchModal = class extends import_obsidian5.FuzzySuggestModal {
  constructor(app, settings, onSelect) {
    super(app);
    this.settings = settings;
    this.onSelect = onSelect;
    this.tasks = [];
    this.loaded = false;
    this.setPlaceholder("Search Asana tasks\u2026");
    this.preload();
  }
  async preload() {
    try {
      const api = new AsanaAPI(this.settings.pat);
      this.tasks = await api.getMyTasks(this.settings.defaultWorkspaceGid);
      this.loaded = true;
    } catch (e) {
    }
  }
  getItems() {
    return this.tasks;
  }
  getItemText(task) {
    return task.name + " " + (task.projects.map((p) => p.name).join(" ") || "");
  }
  onChooseItem(task) {
    this.onSelect(task);
  }
  async onOpen() {
    super.onOpen();
    const inputEl = this.inputEl;
    let debounceTimer;
    inputEl.addEventListener("input", () => {
      window.clearTimeout(debounceTimer);
      const query = inputEl.value.trim();
      if (query.length < 2)
        return;
      debounceTimer = window.setTimeout(async () => {
        try {
          const api = new AsanaAPI(this.settings.pat);
          const results = await api.searchTasks(this.settings.defaultWorkspaceGid, query);
          this.tasks = results;
          this.updateSuggestions();
        } catch (e) {
          new import_obsidian5.Notice("Search failed: " + e.message);
        }
      }, 400);
    });
  }
};

// src/views/TaskListView.ts
var import_obsidian6 = require("obsidian");
var ASANA_TASK_VIEW_TYPE = "asana-task-view";
var AsanaTaskView = class extends import_obsidian6.ItemView {
  constructor(leaf, getSettings) {
    super(leaf);
    this.getSettings = getSettings;
    this.tasks = [];
    this.refreshTimer = null;
  }
  getViewType() {
    return ASANA_TASK_VIEW_TYPE;
  }
  getDisplayText() {
    return "Asana Tasks";
  }
  getIcon() {
    return "check-square";
  }
  async onOpen() {
    await this.refresh();
    this.startAutoRefresh();
  }
  onClose() {
    this.stopAutoRefresh();
    return Promise.resolve();
  }
  startAutoRefresh() {
    this.stopAutoRefresh();
    const interval = this.getSettings().taskListRefreshInterval;
    if (interval > 0) {
      this.refreshTimer = window.setInterval(() => this.refresh(), interval * 1e3);
    }
  }
  stopAutoRefresh() {
    if (this.refreshTimer) {
      window.clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
  }
  async refresh() {
    const settings = this.getSettings();
    const container = this.containerEl.children[1];
    container.empty();
    if (!settings.pat) {
      container.createEl("p", {
        text: "Configure your Asana PAT in plugin settings to get started.",
        cls: "asana-empty"
      });
      return;
    }
    container.createEl("div", { cls: "asana-loading", text: "Loading tasks\u2026" });
    try {
      const api = new AsanaAPI(settings.pat);
      if (!settings.defaultWorkspaceGid) {
        container.empty();
        container.createEl("p", {
          text: 'Set a Default Workspace GID in plugin settings, or click "Connect" to auto-detect.',
          cls: "asana-empty"
        });
        return;
      }
      this.tasks = await api.getMyTasks(settings.defaultWorkspaceGid);
      if (!settings.showCompletedTasks) {
        this.tasks = this.tasks.filter((t) => !t.completed);
      }
      container.empty();
      this.render(container, api);
    } catch (e) {
      container.empty();
      container.createEl("p", { text: "Error: " + e.message, cls: "asana-error" });
    }
  }
  render(container, api) {
    const header = container.createDiv({ cls: "asana-sidebar-header" });
    header.createEl("h4", { text: "My Tasks", cls: "asana-sidebar-title" });
    const controls = header.createDiv({ cls: "asana-sidebar-controls" });
    const refreshBtn = controls.createEl("button", {
      cls: "asana-icon-btn",
      title: "Refresh",
      text: "\u27F3"
    });
    refreshBtn.addEventListener("click", () => this.refresh());
    if (this.tasks.length === 0) {
      container.createEl("p", { text: "No open tasks.", cls: "asana-empty" });
      return;
    }
    const overdue = [];
    const dueToday = [];
    const upcoming = [];
    const noDue = [];
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    for (const task of this.tasks) {
      if (!task.due_on) {
        noDue.push(task);
      } else if (task.due_on < today) {
        overdue.push(task);
      } else if (task.due_on === today) {
        dueToday.push(task);
      } else {
        upcoming.push(task);
      }
    }
    if (overdue.length)
      this.renderSection(container, "\u26A0 Overdue", overdue, api, true);
    if (dueToday.length)
      this.renderSection(container, "Today", dueToday, api);
    if (upcoming.length)
      this.renderSection(container, "Upcoming", upcoming, api);
    if (noDue.length)
      this.renderSection(container, "No due date", noDue, api);
  }
  renderSection(container, title, tasks, api, isOverdue = false) {
    const section = container.createDiv({ cls: "asana-section" });
    section.createEl("h5", {
      text: title,
      cls: "asana-section-title" + (isOverdue ? " asana-overdue-title" : "")
    });
    const list = section.createEl("ul", { cls: "asana-sidebar-list" });
    for (const task of tasks) {
      const li = list.createEl("li", { cls: "asana-sidebar-item" });
      const checkbox = li.createEl("input", {
        type: "checkbox",
        cls: "asana-task-checkbox"
      });
      checkbox.checked = task.completed;
      const info = li.createDiv({ cls: "asana-sidebar-item-info" });
      const link = info.createEl("a", {
        text: task.name,
        href: task.permalink_url,
        cls: "asana-sidebar-task-name"
      });
      if (task.completed)
        link.addClass("asana-completed");
      if (task.projects.length > 0) {
        info.createEl("span", {
          text: task.projects[0].name,
          cls: "asana-sidebar-project"
        });
      }
      checkbox.addEventListener("change", async () => {
        try {
          if (checkbox.checked) {
            await api.completeTask(task.gid);
          } else {
            await api.uncompleteTask(task.gid);
          }
          link.toggleClass("asana-completed", checkbox.checked);
          li.toggleClass("asana-item-done", checkbox.checked);
        } catch (e) {
          checkbox.checked = !checkbox.checked;
          new import_obsidian6.Notice("Failed to update task: " + e.message);
        }
      });
    }
  }
};

// src/main.ts
var AsanaPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(ASANA_TASK_VIEW_TYPE, (leaf) => {
      return new AsanaTaskView(leaf, () => this.settings);
    });
    this.registerMarkdownCodeBlockProcessor("asana-task", (source, el, ctx) => {
      const renderer = new TaskEmbedRenderer(el, source, this.settings);
      ctx.addChild(renderer);
    });
    this.registerMarkdownCodeBlockProcessor("asana-tasks", (source, el, ctx) => {
      const renderer = new TaskListRenderer(el, source, this.settings);
      ctx.addChild(renderer);
    });
    this.addCommand({
      id: "open-task-sidebar",
      name: "Open My Tasks sidebar",
      callback: () => this.activateSidebar()
    });
    this.addCommand({
      id: "create-task",
      name: "Create Asana task",
      callback: () => {
        new CreateTaskModal(this.app, this.settings).open();
      }
    });
    this.addCommand({
      id: "create-task-from-selection",
      name: "Create Asana task from selection and insert link",
      editorCallback: (editor) => {
        const selection = editor.getSelection().trim();
        const modal = new CreateTaskModal(this.app, this.settings, (url, name) => {
          const link = `[${name}](${url})`;
          if (selection) {
            editor.replaceSelection(link);
          } else {
            editor.replaceRange(link, editor.getCursor());
          }
        });
        if (selection) {
          modal.name = selection;
        }
        modal.open();
      }
    });
    this.addCommand({
      id: "search-and-insert-task",
      name: "Search Asana tasks and insert link",
      editorCallback: (editor) => {
        new TaskSearchModal(this.app, this.settings, (task) => {
          const link = `[${task.name}](${task.permalink_url})`;
          editor.replaceRange(link, editor.getCursor());
        }).open();
      }
    });
    this.addCommand({
      id: "search-and-embed-task",
      name: "Search Asana tasks and embed block",
      editorCallback: (editor) => {
        new TaskSearchModal(this.app, this.settings, (task) => {
          const block = `\`\`\`asana-task
${task.gid}
\`\`\`
`;
          editor.replaceRange(block, editor.getCursor());
        }).open();
      }
    });
    this.addCommand({
      id: "link-note-to-task",
      name: "Link this note to an Asana task",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
        if (!view)
          return false;
        if (checking)
          return true;
        new TaskSearchModal(this.app, this.settings, async (task) => {
          const file = view.file;
          if (!file)
            return;
          await this.app.fileManager.processFrontMatter(file, (fm) => {
            fm["asana-task-gid"] = task.gid;
            fm["asana-task-url"] = task.permalink_url;
            fm["asana-task-name"] = task.name;
          });
          new import_obsidian7.Notice(`Note linked to: ${task.name}`);
        }).open();
        return true;
      }
    });
    this.addCommand({
      id: "sync-linked-task",
      name: "Sync linked Asana task status",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
        if (!(view == null ? void 0 : view.file))
          return false;
        if (checking)
          return true;
        this.syncLinkedTask(view.file);
        return true;
      }
    });
    this.addCommand({
      id: "complete-linked-task",
      name: "Complete linked Asana task",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
        if (!(view == null ? void 0 : view.file))
          return false;
        if (checking)
          return true;
        this.toggleLinkedTaskComplete(view.file, true);
        return true;
      }
    });
    this.addRibbonIcon("check-square", "Asana Tasks", () => {
      this.activateSidebar();
    });
    this.addSettingTab(new AsanaSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.pat && this.settings.defaultWorkspaceGid) {
        this.activateSidebar();
      }
    });
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(ASANA_TASK_VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateSidebar() {
    var _a;
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(ASANA_TASK_VIEW_TYPE)[0];
    if (!leaf) {
      leaf = (_a = workspace.getRightLeaf(false)) != null ? _a : workspace.getLeaf(true);
      await leaf.setViewState({ type: ASANA_TASK_VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async syncLinkedTask(file) {
    var _a;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const gid = fm == null ? void 0 : fm["asana-task-gid"];
    if (!gid) {
      new import_obsidian7.Notice("No Asana task linked to this note. Use 'Link this note to an Asana task' first.");
      return;
    }
    try {
      const api = new AsanaAPI(this.settings.pat);
      const task = await api.getTask(gid);
      await this.app.fileManager.processFrontMatter(file, (f) => {
        var _a2, _b, _c;
        f["asana-task-completed"] = task.completed;
        f["asana-task-name"] = task.name;
        f["asana-due-on"] = (_a2 = task.due_on) != null ? _a2 : "";
        f["asana-assignee"] = (_c = (_b = task.assignee) == null ? void 0 : _b.name) != null ? _c : "";
      });
      new import_obsidian7.Notice(`Synced: ${task.name} (${task.completed ? "completed" : "open"})`);
    } catch (e) {
      new import_obsidian7.Notice("Sync failed: " + e.message);
    }
  }
  async toggleLinkedTaskComplete(file, complete) {
    var _a;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const gid = fm == null ? void 0 : fm["asana-task-gid"];
    if (!gid) {
      new import_obsidian7.Notice("No Asana task linked to this note.");
      return;
    }
    try {
      const api = new AsanaAPI(this.settings.pat);
      const task = complete ? await api.completeTask(gid) : await api.uncompleteTask(gid);
      await this.app.fileManager.processFrontMatter(file, (f) => {
        f["asana-task-completed"] = task.completed;
      });
      new import_obsidian7.Notice(`Task marked ${task.completed ? "open" : "complete"}: ${task.name}`);
    } catch (e) {
      new import_obsidian7.Notice("Failed: " + e.message);
    }
  }
};
